<a href="https://colab.research.google.com/github/Sergey-Kiselev-dev/ML_sem_pub/blob/main/ML_04_selfedu_ml_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
SIZE = 1000
np.random.seed(123)
x = np.random.normal(size=SIZE)
y = np.random.normal(size=SIZE)
z = (x + y) / 2
x0 = np.sin(x + y)

F = np.vstack([x, y, z, x0])
FF = 1 / SIZE * F @ F.T
L, W = np.linalg.eig(FF)
WW = sorted(zip(L, W.T), key=lambda lx: lx[0], reverse=True)
WW = np.array([w[1] for w in WW])
print(WW)
print(sorted(L, reverse=True))

[[ 5.73059994e-01  4.50589233e-01  5.11824614e-01  4.54540593e-01]
 [-6.56854592e-01  7.51950945e-01  4.75481766e-02  2.91717871e-02]
 [-2.71067560e-01 -2.54700712e-01 -2.62884136e-01  8.90248199e-01]
 [ 4.08248290e-01  4.08248290e-01 -8.16496581e-01 -8.87886643e-16]]
[1.7215700677714088, 0.9854103505386121, 0.17172757503180333, 4.9553035346903624e-17]
